language: php

dist: trusty

sudo: false

php:
    - 7.2

cache:
    directories:
        - ~/.composer/cache/files

env:
    matrix:
        - SYMFONY_VERSION="3.4.*"
        - SYMFONY_VERSION="4.1.*"

install:
    - composer install --no-interaction --prefer-dist

script:
    - composer validate --strict
    - composer check-style
    - composer analyse
