language: php

dist: trusty

sudo: false

php:
    - 7.2

cache:
    yarn: true
    directories:
        - ~/.composer/cache/files
        - $SYLIUS_CACHE_DIR

env:
    global:
        - SYLIUS_CACHE_DIR=$HOME/.sylius-cache
        - SYLIUS_BUILD_DIR=etc/build
    matrix:
        - SYMFONY_VERSION="3.4.*"
        - SYMFONY_VERSION="4.1.*"

before_install:
    - phpenv config-rm xdebug.ini
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - mkdir -p "${SYLIUS_CACHE_DIR}"
    - mkdir -p tests/Application/web/media/image

    - cp tests/Application/.env.test.dist tests/Application/.env.test
    - set -a && source tests/Application/.env.test && set +a

install:
    - composer require "symfony/browser-kit:${SYMFONY_VERSION}" --no-interaction --no-update
    - composer require "symfony/debug-bundle:${SYMFONY_VERSION}" --no-interaction --no-update
    - composer require "symfony/dotenv:${SYMFONY_VERSION}" --no-interaction --no-update
    - composer require "symfony/intl:${SYMFONY_VERSION}" --no-interaction --no-update
    - composer require "symfony/web-profiler-bundle:${SYMFONY_VERSION}" --no-interaction --no-update
    - composer require "symfony/web-server-bundle:${SYMFONY_VERSION}" --no-interaction --no-update
    - composer install --no-interaction --prefer-dist
    - (cd tests/Application && yarn install)

before_script:
    - (cd tests/Application && bin/console doctrine:database:create --env=test -vvv)
    - (cd tests/Application && bin/console doctrine:schema:create --env=test -vvv)
    - (cd tests/Application && bin/console assets:install public --env=test -vvv)
    - (cd tests/Application && bin/console cache:warmup --env=test -vvv)
    - (cd tests/Application && yarn build)

script:
    - composer validate --strict
    - composer check-style
    - composer analyse

after_failure:
    - vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles "${SYLIUS_BUILD_DIR}/*.log"
